Feat/user discrepancies display
Automattic/newspack-network pull request #100
Opened 2024-05-24 08:52 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1. Enables the "Newspack Network Activity" user column on nodes (previously it was only displayed on the hub)
2. Enhances user count discrepancies debugging columns in the nodes list:

<img width="752" alt="image" src="https://github.com/Automattic/newspack-network/assets/7383192/82f8ef7c-ade7-4cc7-a12b-7266ca7f1610"> 

### How to test the changes in this Pull Request:

1. On your network, create some user discrepancies by deleting some synchronized users directly in the DB (so the deletions are not synchronised), and adding some via CLI (so the additions are not synchronized) 
4. Visit the Nodes view in the hub site, appending a `_newspack_user_discrepancies` param
5. Observe the discrepancies table as visible on the screenshot above, inspect the results to verify if the data matches your specific discrepancies
6. Visit the WP Users view on both a node site and the hub site, observe the "Newspack Network Activity" column is present, with a "View All" link to the hub site's Event Log

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-05-30 18:22 UTC, dkoo approved these changes
Works as described. Non-blocking question: why hide the discrepancies column behind a URL param? It seems broadly useful.

2024-05-30 18:25 UTC, dkoo requested changes
Whoops, I think the counts are flipped. See below

2024-05-30 18:25 UTC, dkoo commented on includes/hub/admin/class-nodes-list.php
> +								sprintf( __( '%1$d on the Hub only, %2$d on the Node only', 'newspack-network' ), count( $not_on_hub ), count( $not_on_node ) )
```suggestion
								sprintf( __( '%1$d on the Hub only, %2$d on the Node only', 'newspack-network' ), count( $not_on_node ), count( $not_on_hub ) )
```

2024-07-01 19:04 UTC, leogermani commented
any reason this PR is staled?

2024-07-01 20:50 UTC, dkoo commented
No reason—just fell off my radar.

2024-07-01 20:50 UTC, dkoo approved these changes

2024-07-02 19:13 UTC, merged