feat: create data event to sync user
Automattic/newspack-network pull request #115
Opened 2024-07-18 21:47 UTC by leogermani

2024-07-22 10:57 UTC, adekbadek reviewed
Let's call site A the site where I'm registering as the new user, and site B the other site.
I do see `Executing action handlers for "network_new_reader".` in the site B logs only and `Normalizing contact data for reader ESP sync:` is site A logs only. Is this expected? From the testing instructions I assume both log lines should be visible in site B's logs.

2024-07-25 22:20 UTC, dkoo requested changes
I'm running into an error on the site receiving the new network reader event. The normalized data is missing an email address:

```
[25-Jul-2024 22:16:13 UTC] [10980][NEWSPACK][Newspack\Newspack_Newsletters::normalize_contact_data]: {
    "email": "",
    "metadata": {
        "NP_Account": 31,
        "NP_Registration Date": "2024-07-25",
        "NP_Membership Status": "",
        "NP_Product Name": "",
        "NP_Network Registration Site": "https:\/\/node-site.test",
        "status": "subscribed"
    },
    "existing_contact_data": false
}
```

which causes the Mailchimp API request to update the contact to return a 400 response with an error `Search query string must be non-empty, try again`. I figured this out because I kept seeing `PHP Warning:  Undefined array key "exact_matches" in /newspack-repos/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php on line 1584` in the log and saw that the contact doesn't get synced from the receiving site.

2024-07-26 21:37 UTC, leogermani commented
Thanks @adekbadek and @dkoo 

> From the testing instructions I assume both log lines should be visible in site B's logs.

That's correct. Both things should be visible on site B. Make sure RAS is enabled on site B, sync to ESP is turned on and that there is a Master List/Audience selected.

> The normalized data is missing an email address:

Fixed!

2024-07-29 08:58 UTC, adekbadek commented
> Both [log lines] should be visible on site B.

When testing again, it's still [the same](https://github.com/Automattic/newspack-network/pull/115#pullrequestreview-2191266180).

2024-07-29 13:25 UTC, leogermani commented
> > Both [log lines] should be visible on site B.
> 
> When testing again, it's still [the same](https://github.com/Automattic/newspack-network/pull/115#pullrequestreview-2191266180).

Can you see the contact beeing synced to the ESP? 

One thing I corrected in the testing instructions that I forgot to mention is that you also need to checkout newspack-newsletters on `epic/consolidate-data-flows`.

@dkoo Do you see the logs and the sync happening?

2024-07-29 21:40 UTC, dkoo commented
> @dkoo Do you see the logs and the sync happening?

No, I'm still seeing the same behavior. Did you forget to push the fix to the remote?

2024-07-29 21:50 UTC, leogermani commented
I thought I was going crazy for a moment, but the fix for this was mistakenly committed directly to the epic branch on the main plugin here -> https://github.com/Automattic/newspack-plugin/commit/efaa47fad6b36caae60938628357f3d310b3eb59

I guess with all the branches / plugins switches I thought I was pushing the fix to this branch, but it turns out to be in another plugin :) 

So you need to make sure to update your main plugin in the `epic/consolidate-data-flows` branch. sorry

2024-07-29 22:41 UTC, dkoo approved these changes
@leogermani thanks for clarifying! After updating the other plugins to the correct branches, I now see the `network_new_reader` event happening on site B (the one receiving the network reader) and I see the sync getting triggered there as well.

2024-07-30 20:57 UTC, leogermani commented
Thanks @dkoo 

FYI, https://github.com/Automattic/newspack-network/pull/115/commits/9c5d3f3cd02ba485473cfa2ec3a013dea1bbaeda is not a big deal, and should not make a difference in production. But for my local sites, the local URLs were not passing that validation and the event was being triggered with the wrong URL there. I think it's fine to leave it without that check because we are not doing anything dangerous with it

2024-08-01 21:55 UTC, merged