feat: add CLI command for distribute post
Automattic/newspack-network pull request #159
Opened 2024-12-09 12:04 UTC by naxoc

This is work in progress.

2024-12-11 15:01 UTC, miguelpeixe requested changes
Tests well and the code looks good!

I have a couple of questions inline

2024-12-11 15:01 UTC, miguelpeixe commented on includes/cli/class-distribution.php
> +			}
This seems like a useful logic to be in `Outgoing_Post->set_config()` instead of here. WDYT?

2024-12-11 15:01 UTC, miguelpeixe commented on includes/cli/class-distribution.php
> +			$outgoing_post->set_config( $sites );
I wonder if it'd be expected behavior for a command to overwrite any previously configured sites. I can see a case where a post is being distributed to a site and the admin would like to add a new one when running the command.

2024-12-11 15:01 UTC, miguelpeixe commented on includes/content-distribution/class-outgoing-post.php
> +
💯

2024-12-11 15:05 UTC, naxoc commented on includes/cli/class-distribution.php
> +			}
That makes sense. I'll move it!

2024-12-11 15:06 UTC, naxoc commented on includes/cli/class-distribution.php
> +			$outgoing_post->set_config( $sites );
Yeah, I was not sure either. It might be better if I only add the sites missing in the config?

2024-12-11 15:08 UTC, miguelpeixe commented on includes/cli/class-distribution.php
> +			$outgoing_post->set_config( $sites );
It might, but that would warrant a way to remove sites from the config.

Maybe we can leave `--sites` as is and add a `--add-sites` to append.

2024-12-11 16:32 UTC, naxoc commented on includes/cli/class-distribution.php
> +			}
I'm now debug logging it if a url was passed that is not networked.

2024-12-12 15:43 UTC, naxoc commented on includes/cli/class-distribution.php
> +			$outgoing_post->set_config( $sites );
I made it so we can add sites with `--sites`. We can't remove ones though.

2024-12-12 15:44 UTC, naxoc commented
OK, @miguelpeixe – I had to update the test a bit with some mockery, but I think this is ready for re-review. 

Note that the `set_config()` now returns the config – I use it to write a message to the CLI. Let me know if that makes no sense.

2024-12-12 17:34 UTC, miguelpeixe requested changes
That's perfect! Thank you for all the revisions 🎉 

One nitpicky thing below

2024-12-12 17:34 UTC, miguelpeixe commented on includes/content-distribution/class-outgoing-post.php
> +		$config['site_urls'] = array_unique( array_merge( $config['site_urls'], $site_urls ) );
Can we unit test this new thing?

2024-12-12 17:56 UTC, naxoc commented on includes/content-distribution/class-outgoing-post.php
> +		$config['site_urls'] = array_unique( array_merge( $config['site_urls'], $site_urls ) );
Yep! I added a test 👍

2024-12-12 18:05 UTC, miguelpeixe approved these changes

2024-12-12 19:58 UTC, merged