Assorted changes
Automattic/newspack-network pull request #94
Opened 2024-04-25 14:47 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1. Changes the environment variable name used to enable the experimental auditing features
2. Adds ESP contact "Network Registration Site" meta field on network reader creation or fetch (contribution originally by @dkoo committed to the `data-integrity-improvements` branch)
3. Adds more data to backfilled users
4. Fixes membership event timestamp for backfilled memberships 

### How to test the changes in this Pull Request:

1. Set `NEWSPACK_NETWORK_EXPERIMENTAL_AUDITING_FEATURES` environment variable to `true`, visit Newspack Network -> Nodes and the admin panel and observe there's a "Synchronizable Users" column present
5. With Mailchimp or ActiveCampaign set as the ESP, register a new reader on a site
6. In the ESP UI, observe the contact has a custom field "Network Registration Site" with the origin site assigned
7. Disable this plugin on the Hub site and create a new user (with a first and last name), and a membership
8. Enable this plugin and run the backfill CLI: `wp newspack-network data-backfill all --start=2020-01-01 --end=2024-12-31 --live`
9. Visit the Event Log and observe the `user_registered` event has the first and last name in the event data
10. Observe the membership event has the timestamp same as the membership start date

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-04-26 18:13 UTC, dkoo requested changes
This is working great! The only issue I see is that when running the backfill script, it's fetching users only who registered on the site you're running the script on (so actual customer or subscriber users, not network_reader users). These users won't have the `newspack_remote_site` user meta, as this meta is only populated on network_reader users. So we'll need to manually add the `network_registration_site` meta when syncing to the ESP and assume that the registration site is the current site URL.

2024-05-08 14:00 UTC, adekbadek commented
@dkoo – 

> it's fetching users only who registered on the site you're running the script on […] These users won't have the `newspack_remote_site` user meta

That's expected, the "original" users never have the `newspack_remote_site` user meta assigned, because the site is their origin. The backfill script does not change anything in that regard, unless I'm misreading your comment. 

> So we'll need to […] assume that the registration site is the current site URL.

Precisely! This is how this plugin worked all the time.

2024-05-08 22:01 UTC, dkoo commented
> That's expected, the "original" users never have the newspack_remote_site user meta assigned, because the site is their origin. The backfill script does not change anything in that regard, unless I'm misreading your comment.

Got it, so just to clarify: the backfill script in this PR is only concerned with backfilling registration events for "original" user accounts. So the `network_registration_site` metadata will be populated on the _other_ backfill process, when we sync contact data for all users (not just original ones, but also `network_reader` users) to the connected ESP.

2024-05-08 22:01 UTC, dkoo approved these changes

2024-05-09 07:10 UTC, adekbadek commented
That's correct. The backfill script in this PR is supposed to be ran on each network site, and _then_ the events will be synchronised.

2024-05-09 07:11 UTC, merged